### ISSUE TITLE
Test specification

### ISSUE THREAD

**Issue by 0hsn** [chkware/cli#88]
- [x] #89
- [x] `test-spec` document schema setup and validation
- [x] execute:self type of `test-spec` with minimum request items
- [x] execute:file type of `test-spec` with minimum request items
- [x] #115
- [x] #116
- [x] #112 
- [ ] Support for external http spec files
